services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
